sudo: required

branches:
  only:
    - /^\d{10}$/

services:
  - docker

env:
  global:
    - GIT_NAME: "Richard Chien"
    - GIT_EMAIL: richardchienthebest@gmail.com
    - DOCKER_USER: richardchien
    - DOCKER_REPO: richardchien/ctb

script:
  - export DOCKER_TAG=${TRAVIS_TAG#v}
  - docker build -t $DOCKER_REPO:$DOCKER_TAG --build-arg GIT_TAG=$TRAVIS_TAG --no-cache .

after_success:
  - docker tag $DOCKER_REPO:$DOCKER_TAG $DOCKER_REPO:latest
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $DOCKER_REPO
